apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-service
  namespace: healthsync
spec:
  schedule: "*/5 * * * *"# Schedule to every 5 min
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator-service
            image: 553580522931.dkr.ecr.ap-southeast-1.amazonaws.com/healthsync/aggregator-service:latest
            command: ["python", "aggregator_service.py"]
            args: ["--run-aggregation"]
            env:
            - name: RDS_DB_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: RDS_DB_URI
            imagePullPolicy: Always
            resources:
              limits:
                memory: "512Mi"
                cpu: "500m"
              requests:
                memory: "256Mi"
                cpu: "250m"
          restartPolicy: OnFailure
